name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/austenstone/action-docker:sha-c2a395aeaa432ad387a23374c8c3da3f083161de"
  args:
    - ${{ inputs.token }}
